<?php

/**
 * ThanaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ThanaTable extends PluginThanaTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ThanaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Thana');
    }
}