<?php

/**
 * PluginSubjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSubjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSubjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSubject');
    }
}