<?php

/**
 * PluginReligionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginReligionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginReligionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginReligion');
    }
}