<?php

/**
 * PluginDivisionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDivisionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDivisionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDivision');
    }
}