<?php

/**
 * PluginDistrictTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDistrictTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDistrictTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDistrict');
    }
}