<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('HsHrEmployee', 'doctrine');

/**
 * BaseHsHrEmployee
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $emp_number
 * @property string $employee_id
 * @property string $emp_lastname
 * @property string $emp_firstname
 * @property string $emp_middle_name
 * @property string $emp_nick_name
 * @property integer $emp_smoker
 * @property string $ethnic_race_code
 * @property date $emp_birthday
 * @property integer $nation_code
 * @property integer $emp_gender
 * @property string $emp_marital_status
 * @property string $emp_ssn_num
 * @property string $emp_sin_num
 * @property string $emp_other_id
 * @property string $emp_dri_lice_num
 * @property date $emp_dri_lice_exp_date
 * @property string $emp_military_service
 * @property integer $emp_status
 * @property integer $job_title_code
 * @property integer $eeo_cat_code
 * @property integer $work_station
 * @property string $emp_street1
 * @property string $emp_street2
 * @property string $city_code
 * @property string $coun_code
 * @property string $provin_code
 * @property string $emp_zipcode
 * @property string $emp_hm_telephone
 * @property string $emp_mobile
 * @property string $emp_work_telephone
 * @property string $emp_work_email
 * @property string $sal_grd_code
 * @property date $joined_date
 * @property string $emp_oth_email
 * @property integer $termination_id
 * @property string $custom1
 * @property string $custom2
 * @property string $custom3
 * @property string $custom4
 * @property string $custom5
 * @property string $custom6
 * @property string $custom7
 * @property string $custom8
 * @property string $custom9
 * @property string $custom10
 * @property OhrmSubunit $OhrmSubunit
 * @property OhrmNationality $OhrmNationality
 * @property OhrmJobTitle $OhrmJobTitle
 * @property OhrmEmploymentStatus $OhrmEmploymentStatus
 * @property OhrmJobCategory $OhrmJobCategory
 * @property Doctrine_Collection $OhrmEmpTermination
 * @property Doctrine_Collection $HsHrEmpAttachment
 * @property Doctrine_Collection $HsHrEmpBasicsalary
 * @property Doctrine_Collection $HsHrEmpChildren
 * @property Doctrine_Collection $HsHrEmpContractExtend
 * @property Doctrine_Collection $HsHrEmpDependents
 * @property Doctrine_Collection $HsHrEmpEmergencyContacts
 * @property Doctrine_Collection $HsHrEmpHistoryOfEalierPos
 * @property Doctrine_Collection $HsHrEmpLanguage
 * @property Doctrine_Collection $HsHrEmpLocations
 * @property Doctrine_Collection $HsHrEmpMemberDetail
 * @property Doctrine_Collection $HsHrEmpPassport
 * @property Doctrine_Collection $HsHrEmpPicture
 * @property Doctrine_Collection $HsHrEmpReportto
 * @property Doctrine_Collection $HsHrEmpReportto_2
 * @property Doctrine_Collection $HsHrEmpSkill
 * @property Doctrine_Collection $HsHrEmpUsTax
 * @property Doctrine_Collection $HsHrEmpWorkExperience
 * @property Doctrine_Collection $OhrmEmpEducation
 * @property Doctrine_Collection $OhrmEmpLicense
 * @property Doctrine_Collection $OhrmEmployeeWorkShift
 * @property Doctrine_Collection $OhrmJobCandidate
 * @property Doctrine_Collection $OhrmJobCandidateHistory
 * @property Doctrine_Collection $OhrmJobInterviewInterviewer
 * @property Doctrine_Collection $OhrmJobVacancy
 * @property Doctrine_Collection $OhrmLeaveAdjustment
 * @property Doctrine_Collection $OhrmLeaveComment
 * @property Doctrine_Collection $OhrmLeaveEntitlement
 * @property Doctrine_Collection $OhrmLeaveRequest
 * @property Doctrine_Collection $OhrmLeaveRequestComment
 * @property Doctrine_Collection $OhrmPerformanceReview
 * @property Doctrine_Collection $OhrmPerformanceTrack
 * @property Doctrine_Collection $OhrmPerformanceTrack_2
 * @property Doctrine_Collection $OhrmPerformanceTrackerLog
 * @property Doctrine_Collection $OhrmPerformanceTrackerReviewer
 * @property Doctrine_Collection $OhrmProjectAdmin
 * @property Doctrine_Collection $OhrmUser
 * 
 * @method integer              getEmpNumber()                      Returns the current record's "emp_number" value
 * @method string               getEmployeeId()                     Returns the current record's "employee_id" value
 * @method string               getEmpLastname()                    Returns the current record's "emp_lastname" value
 * @method string               getEmpFirstname()                   Returns the current record's "emp_firstname" value
 * @method string               getEmpMiddleName()                  Returns the current record's "emp_middle_name" value
 * @method string               getEmpNickName()                    Returns the current record's "emp_nick_name" value
 * @method integer              getEmpSmoker()                      Returns the current record's "emp_smoker" value
 * @method string               getEthnicRaceCode()                 Returns the current record's "ethnic_race_code" value
 * @method date                 getEmpBirthday()                    Returns the current record's "emp_birthday" value
 * @method integer              getNationCode()                     Returns the current record's "nation_code" value
 * @method integer              getEmpGender()                      Returns the current record's "emp_gender" value
 * @method string               getEmpMaritalStatus()               Returns the current record's "emp_marital_status" value
 * @method string               getEmpSsnNum()                      Returns the current record's "emp_ssn_num" value
 * @method string               getEmpSinNum()                      Returns the current record's "emp_sin_num" value
 * @method string               getEmpOtherId()                     Returns the current record's "emp_other_id" value
 * @method string               getEmpDriLiceNum()                  Returns the current record's "emp_dri_lice_num" value
 * @method date                 getEmpDriLiceExpDate()              Returns the current record's "emp_dri_lice_exp_date" value
 * @method string               getEmpMilitaryService()             Returns the current record's "emp_military_service" value
 * @method integer              getEmpStatus()                      Returns the current record's "emp_status" value
 * @method integer              getJobTitleCode()                   Returns the current record's "job_title_code" value
 * @method integer              getEeoCatCode()                     Returns the current record's "eeo_cat_code" value
 * @method integer              getWorkStation()                    Returns the current record's "work_station" value
 * @method string               getEmpStreet1()                     Returns the current record's "emp_street1" value
 * @method string               getEmpStreet2()                     Returns the current record's "emp_street2" value
 * @method string               getCityCode()                       Returns the current record's "city_code" value
 * @method string               getCounCode()                       Returns the current record's "coun_code" value
 * @method string               getProvinCode()                     Returns the current record's "provin_code" value
 * @method string               getEmpZipcode()                     Returns the current record's "emp_zipcode" value
 * @method string               getEmpHmTelephone()                 Returns the current record's "emp_hm_telephone" value
 * @method string               getEmpMobile()                      Returns the current record's "emp_mobile" value
 * @method string               getEmpWorkTelephone()               Returns the current record's "emp_work_telephone" value
 * @method string               getEmpWorkEmail()                   Returns the current record's "emp_work_email" value
 * @method string               getSalGrdCode()                     Returns the current record's "sal_grd_code" value
 * @method date                 getJoinedDate()                     Returns the current record's "joined_date" value
 * @method string               getEmpOthEmail()                    Returns the current record's "emp_oth_email" value
 * @method integer              getTerminationId()                  Returns the current record's "termination_id" value
 * @method string               getCustom1()                        Returns the current record's "custom1" value
 * @method string               getCustom2()                        Returns the current record's "custom2" value
 * @method string               getCustom3()                        Returns the current record's "custom3" value
 * @method string               getCustom4()                        Returns the current record's "custom4" value
 * @method string               getCustom5()                        Returns the current record's "custom5" value
 * @method string               getCustom6()                        Returns the current record's "custom6" value
 * @method string               getCustom7()                        Returns the current record's "custom7" value
 * @method string               getCustom8()                        Returns the current record's "custom8" value
 * @method string               getCustom9()                        Returns the current record's "custom9" value
 * @method string               getCustom10()                       Returns the current record's "custom10" value
 * @method OhrmSubunit          getOhrmSubunit()                    Returns the current record's "OhrmSubunit" value
 * @method OhrmNationality      getOhrmNationality()                Returns the current record's "OhrmNationality" value
 * @method OhrmJobTitle         getOhrmJobTitle()                   Returns the current record's "OhrmJobTitle" value
 * @method OhrmEmploymentStatus getOhrmEmploymentStatus()           Returns the current record's "OhrmEmploymentStatus" value
 * @method OhrmJobCategory      getOhrmJobCategory()                Returns the current record's "OhrmJobCategory" value
 * @method Doctrine_Collection  getOhrmEmpTermination()             Returns the current record's "OhrmEmpTermination" collection
 * @method Doctrine_Collection  getHsHrEmpAttachment()              Returns the current record's "HsHrEmpAttachment" collection
 * @method Doctrine_Collection  getHsHrEmpBasicsalary()             Returns the current record's "HsHrEmpBasicsalary" collection
 * @method Doctrine_Collection  getHsHrEmpChildren()                Returns the current record's "HsHrEmpChildren" collection
 * @method Doctrine_Collection  getHsHrEmpContractExtend()          Returns the current record's "HsHrEmpContractExtend" collection
 * @method Doctrine_Collection  getHsHrEmpDependents()              Returns the current record's "HsHrEmpDependents" collection
 * @method Doctrine_Collection  getHsHrEmpEmergencyContacts()       Returns the current record's "HsHrEmpEmergencyContacts" collection
 * @method Doctrine_Collection  getHsHrEmpHistoryOfEalierPos()      Returns the current record's "HsHrEmpHistoryOfEalierPos" collection
 * @method Doctrine_Collection  getHsHrEmpLanguage()                Returns the current record's "HsHrEmpLanguage" collection
 * @method Doctrine_Collection  getHsHrEmpLocations()               Returns the current record's "HsHrEmpLocations" collection
 * @method Doctrine_Collection  getHsHrEmpMemberDetail()            Returns the current record's "HsHrEmpMemberDetail" collection
 * @method Doctrine_Collection  getHsHrEmpPassport()                Returns the current record's "HsHrEmpPassport" collection
 * @method Doctrine_Collection  getHsHrEmpPicture()                 Returns the current record's "HsHrEmpPicture" collection
 * @method Doctrine_Collection  getHsHrEmpReportto()                Returns the current record's "HsHrEmpReportto" collection
 * @method Doctrine_Collection  getHsHrEmpReportto2()               Returns the current record's "HsHrEmpReportto_2" collection
 * @method Doctrine_Collection  getHsHrEmpSkill()                   Returns the current record's "HsHrEmpSkill" collection
 * @method Doctrine_Collection  getHsHrEmpUsTax()                   Returns the current record's "HsHrEmpUsTax" collection
 * @method Doctrine_Collection  getHsHrEmpWorkExperience()          Returns the current record's "HsHrEmpWorkExperience" collection
 * @method Doctrine_Collection  getOhrmEmpEducation()               Returns the current record's "OhrmEmpEducation" collection
 * @method Doctrine_Collection  getOhrmEmpLicense()                 Returns the current record's "OhrmEmpLicense" collection
 * @method Doctrine_Collection  getOhrmEmployeeWorkShift()          Returns the current record's "OhrmEmployeeWorkShift" collection
 * @method Doctrine_Collection  getOhrmJobCandidate()               Returns the current record's "OhrmJobCandidate" collection
 * @method Doctrine_Collection  getOhrmJobCandidateHistory()        Returns the current record's "OhrmJobCandidateHistory" collection
 * @method Doctrine_Collection  getOhrmJobInterviewInterviewer()    Returns the current record's "OhrmJobInterviewInterviewer" collection
 * @method Doctrine_Collection  getOhrmJobVacancy()                 Returns the current record's "OhrmJobVacancy" collection
 * @method Doctrine_Collection  getOhrmLeaveAdjustment()            Returns the current record's "OhrmLeaveAdjustment" collection
 * @method Doctrine_Collection  getOhrmLeaveComment()               Returns the current record's "OhrmLeaveComment" collection
 * @method Doctrine_Collection  getOhrmLeaveEntitlement()           Returns the current record's "OhrmLeaveEntitlement" collection
 * @method Doctrine_Collection  getOhrmLeaveRequest()               Returns the current record's "OhrmLeaveRequest" collection
 * @method Doctrine_Collection  getOhrmLeaveRequestComment()        Returns the current record's "OhrmLeaveRequestComment" collection
 * @method Doctrine_Collection  getOhrmPerformanceReview()          Returns the current record's "OhrmPerformanceReview" collection
 * @method Doctrine_Collection  getOhrmPerformanceTrack()           Returns the current record's "OhrmPerformanceTrack" collection
 * @method Doctrine_Collection  getOhrmPerformanceTrack2()          Returns the current record's "OhrmPerformanceTrack_2" collection
 * @method Doctrine_Collection  getOhrmPerformanceTrackerLog()      Returns the current record's "OhrmPerformanceTrackerLog" collection
 * @method Doctrine_Collection  getOhrmPerformanceTrackerReviewer() Returns the current record's "OhrmPerformanceTrackerReviewer" collection
 * @method Doctrine_Collection  getOhrmProjectAdmin()               Returns the current record's "OhrmProjectAdmin" collection
 * @method Doctrine_Collection  getOhrmUser()                       Returns the current record's "OhrmUser" collection
 * @method HsHrEmployee         setEmpNumber()                      Sets the current record's "emp_number" value
 * @method HsHrEmployee         setEmployeeId()                     Sets the current record's "employee_id" value
 * @method HsHrEmployee         setEmpLastname()                    Sets the current record's "emp_lastname" value
 * @method HsHrEmployee         setEmpFirstname()                   Sets the current record's "emp_firstname" value
 * @method HsHrEmployee         setEmpMiddleName()                  Sets the current record's "emp_middle_name" value
 * @method HsHrEmployee         setEmpNickName()                    Sets the current record's "emp_nick_name" value
 * @method HsHrEmployee         setEmpSmoker()                      Sets the current record's "emp_smoker" value
 * @method HsHrEmployee         setEthnicRaceCode()                 Sets the current record's "ethnic_race_code" value
 * @method HsHrEmployee         setEmpBirthday()                    Sets the current record's "emp_birthday" value
 * @method HsHrEmployee         setNationCode()                     Sets the current record's "nation_code" value
 * @method HsHrEmployee         setEmpGender()                      Sets the current record's "emp_gender" value
 * @method HsHrEmployee         setEmpMaritalStatus()               Sets the current record's "emp_marital_status" value
 * @method HsHrEmployee         setEmpSsnNum()                      Sets the current record's "emp_ssn_num" value
 * @method HsHrEmployee         setEmpSinNum()                      Sets the current record's "emp_sin_num" value
 * @method HsHrEmployee         setEmpOtherId()                     Sets the current record's "emp_other_id" value
 * @method HsHrEmployee         setEmpDriLiceNum()                  Sets the current record's "emp_dri_lice_num" value
 * @method HsHrEmployee         setEmpDriLiceExpDate()              Sets the current record's "emp_dri_lice_exp_date" value
 * @method HsHrEmployee         setEmpMilitaryService()             Sets the current record's "emp_military_service" value
 * @method HsHrEmployee         setEmpStatus()                      Sets the current record's "emp_status" value
 * @method HsHrEmployee         setJobTitleCode()                   Sets the current record's "job_title_code" value
 * @method HsHrEmployee         setEeoCatCode()                     Sets the current record's "eeo_cat_code" value
 * @method HsHrEmployee         setWorkStation()                    Sets the current record's "work_station" value
 * @method HsHrEmployee         setEmpStreet1()                     Sets the current record's "emp_street1" value
 * @method HsHrEmployee         setEmpStreet2()                     Sets the current record's "emp_street2" value
 * @method HsHrEmployee         setCityCode()                       Sets the current record's "city_code" value
 * @method HsHrEmployee         setCounCode()                       Sets the current record's "coun_code" value
 * @method HsHrEmployee         setProvinCode()                     Sets the current record's "provin_code" value
 * @method HsHrEmployee         setEmpZipcode()                     Sets the current record's "emp_zipcode" value
 * @method HsHrEmployee         setEmpHmTelephone()                 Sets the current record's "emp_hm_telephone" value
 * @method HsHrEmployee         setEmpMobile()                      Sets the current record's "emp_mobile" value
 * @method HsHrEmployee         setEmpWorkTelephone()               Sets the current record's "emp_work_telephone" value
 * @method HsHrEmployee         setEmpWorkEmail()                   Sets the current record's "emp_work_email" value
 * @method HsHrEmployee         setSalGrdCode()                     Sets the current record's "sal_grd_code" value
 * @method HsHrEmployee         setJoinedDate()                     Sets the current record's "joined_date" value
 * @method HsHrEmployee         setEmpOthEmail()                    Sets the current record's "emp_oth_email" value
 * @method HsHrEmployee         setTerminationId()                  Sets the current record's "termination_id" value
 * @method HsHrEmployee         setCustom1()                        Sets the current record's "custom1" value
 * @method HsHrEmployee         setCustom2()                        Sets the current record's "custom2" value
 * @method HsHrEmployee         setCustom3()                        Sets the current record's "custom3" value
 * @method HsHrEmployee         setCustom4()                        Sets the current record's "custom4" value
 * @method HsHrEmployee         setCustom5()                        Sets the current record's "custom5" value
 * @method HsHrEmployee         setCustom6()                        Sets the current record's "custom6" value
 * @method HsHrEmployee         setCustom7()                        Sets the current record's "custom7" value
 * @method HsHrEmployee         setCustom8()                        Sets the current record's "custom8" value
 * @method HsHrEmployee         setCustom9()                        Sets the current record's "custom9" value
 * @method HsHrEmployee         setCustom10()                       Sets the current record's "custom10" value
 * @method HsHrEmployee         setOhrmSubunit()                    Sets the current record's "OhrmSubunit" value
 * @method HsHrEmployee         setOhrmNationality()                Sets the current record's "OhrmNationality" value
 * @method HsHrEmployee         setOhrmJobTitle()                   Sets the current record's "OhrmJobTitle" value
 * @method HsHrEmployee         setOhrmEmploymentStatus()           Sets the current record's "OhrmEmploymentStatus" value
 * @method HsHrEmployee         setOhrmJobCategory()                Sets the current record's "OhrmJobCategory" value
 * @method HsHrEmployee         setOhrmEmpTermination()             Sets the current record's "OhrmEmpTermination" collection
 * @method HsHrEmployee         setHsHrEmpAttachment()              Sets the current record's "HsHrEmpAttachment" collection
 * @method HsHrEmployee         setHsHrEmpBasicsalary()             Sets the current record's "HsHrEmpBasicsalary" collection
 * @method HsHrEmployee         setHsHrEmpChildren()                Sets the current record's "HsHrEmpChildren" collection
 * @method HsHrEmployee         setHsHrEmpContractExtend()          Sets the current record's "HsHrEmpContractExtend" collection
 * @method HsHrEmployee         setHsHrEmpDependents()              Sets the current record's "HsHrEmpDependents" collection
 * @method HsHrEmployee         setHsHrEmpEmergencyContacts()       Sets the current record's "HsHrEmpEmergencyContacts" collection
 * @method HsHrEmployee         setHsHrEmpHistoryOfEalierPos()      Sets the current record's "HsHrEmpHistoryOfEalierPos" collection
 * @method HsHrEmployee         setHsHrEmpLanguage()                Sets the current record's "HsHrEmpLanguage" collection
 * @method HsHrEmployee         setHsHrEmpLocations()               Sets the current record's "HsHrEmpLocations" collection
 * @method HsHrEmployee         setHsHrEmpMemberDetail()            Sets the current record's "HsHrEmpMemberDetail" collection
 * @method HsHrEmployee         setHsHrEmpPassport()                Sets the current record's "HsHrEmpPassport" collection
 * @method HsHrEmployee         setHsHrEmpPicture()                 Sets the current record's "HsHrEmpPicture" collection
 * @method HsHrEmployee         setHsHrEmpReportto()                Sets the current record's "HsHrEmpReportto" collection
 * @method HsHrEmployee         setHsHrEmpReportto2()               Sets the current record's "HsHrEmpReportto_2" collection
 * @method HsHrEmployee         setHsHrEmpSkill()                   Sets the current record's "HsHrEmpSkill" collection
 * @method HsHrEmployee         setHsHrEmpUsTax()                   Sets the current record's "HsHrEmpUsTax" collection
 * @method HsHrEmployee         setHsHrEmpWorkExperience()          Sets the current record's "HsHrEmpWorkExperience" collection
 * @method HsHrEmployee         setOhrmEmpEducation()               Sets the current record's "OhrmEmpEducation" collection
 * @method HsHrEmployee         setOhrmEmpLicense()                 Sets the current record's "OhrmEmpLicense" collection
 * @method HsHrEmployee         setOhrmEmployeeWorkShift()          Sets the current record's "OhrmEmployeeWorkShift" collection
 * @method HsHrEmployee         setOhrmJobCandidate()               Sets the current record's "OhrmJobCandidate" collection
 * @method HsHrEmployee         setOhrmJobCandidateHistory()        Sets the current record's "OhrmJobCandidateHistory" collection
 * @method HsHrEmployee         setOhrmJobInterviewInterviewer()    Sets the current record's "OhrmJobInterviewInterviewer" collection
 * @method HsHrEmployee         setOhrmJobVacancy()                 Sets the current record's "OhrmJobVacancy" collection
 * @method HsHrEmployee         setOhrmLeaveAdjustment()            Sets the current record's "OhrmLeaveAdjustment" collection
 * @method HsHrEmployee         setOhrmLeaveComment()               Sets the current record's "OhrmLeaveComment" collection
 * @method HsHrEmployee         setOhrmLeaveEntitlement()           Sets the current record's "OhrmLeaveEntitlement" collection
 * @method HsHrEmployee         setOhrmLeaveRequest()               Sets the current record's "OhrmLeaveRequest" collection
 * @method HsHrEmployee         setOhrmLeaveRequestComment()        Sets the current record's "OhrmLeaveRequestComment" collection
 * @method HsHrEmployee         setOhrmPerformanceReview()          Sets the current record's "OhrmPerformanceReview" collection
 * @method HsHrEmployee         setOhrmPerformanceTrack()           Sets the current record's "OhrmPerformanceTrack" collection
 * @method HsHrEmployee         setOhrmPerformanceTrack2()          Sets the current record's "OhrmPerformanceTrack_2" collection
 * @method HsHrEmployee         setOhrmPerformanceTrackerLog()      Sets the current record's "OhrmPerformanceTrackerLog" collection
 * @method HsHrEmployee         setOhrmPerformanceTrackerReviewer() Sets the current record's "OhrmPerformanceTrackerReviewer" collection
 * @method HsHrEmployee         setOhrmProjectAdmin()               Sets the current record's "OhrmProjectAdmin" collection
 * @method HsHrEmployee         setOhrmUser()                       Sets the current record's "OhrmUser" collection
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHsHrEmployee extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_employee');
        $this->hasColumn('emp_number', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('employee_id', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('emp_lastname', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('emp_firstname', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('emp_middle_name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('emp_nick_name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('emp_smoker', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('ethnic_race_code', 'string', 13, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 13,
             ));
        $this->hasColumn('emp_birthday', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('nation_code', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('emp_gender', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('emp_marital_status', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('emp_ssn_num', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('emp_sin_num', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('emp_other_id', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('emp_dri_lice_num', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('emp_dri_lice_exp_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('emp_military_service', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('emp_status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('job_title_code', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('eeo_cat_code', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('work_station', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('emp_street1', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('emp_street2', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('city_code', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('coun_code', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('provin_code', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('emp_zipcode', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('emp_hm_telephone', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('emp_mobile', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('emp_work_telephone', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('emp_work_email', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('sal_grd_code', 'string', 13, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 13,
             ));
        $this->hasColumn('joined_date', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('emp_oth_email', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('termination_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('custom1', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('custom2', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('custom3', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('custom4', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('custom5', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('custom6', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('custom7', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('custom8', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('custom9', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('custom10', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('OhrmSubunit', array(
             'local' => 'work_station',
             'foreign' => 'id'));

        $this->hasOne('OhrmNationality', array(
             'local' => 'nation_code',
             'foreign' => 'id'));

        $this->hasOne('OhrmJobTitle', array(
             'local' => 'job_title_code',
             'foreign' => 'id'));

        $this->hasOne('OhrmEmploymentStatus', array(
             'local' => 'emp_status',
             'foreign' => 'id'));

        $this->hasOne('OhrmJobCategory', array(
             'local' => 'eeo_cat_code',
             'foreign' => 'id'));

        $this->hasMany('OhrmEmpTermination', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('HsHrEmpAttachment', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('HsHrEmpBasicsalary', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('HsHrEmpChildren', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('HsHrEmpContractExtend', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('HsHrEmpDependents', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('HsHrEmpEmergencyContacts', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('HsHrEmpHistoryOfEalierPos', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('HsHrEmpLanguage', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('HsHrEmpLocations', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('HsHrEmpMemberDetail', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('HsHrEmpPassport', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('HsHrEmpPicture', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('HsHrEmpReportto', array(
             'local' => 'emp_number',
             'foreign' => 'erep_sup_emp_number'));

        $this->hasMany('HsHrEmpReportto as HsHrEmpReportto_2', array(
             'local' => 'emp_number',
             'foreign' => 'erep_sub_emp_number'));

        $this->hasMany('HsHrEmpSkill', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('HsHrEmpUsTax', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('HsHrEmpWorkExperience', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('OhrmEmpEducation', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('OhrmEmpLicense', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('OhrmEmployeeWorkShift', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('OhrmJobCandidate', array(
             'local' => 'emp_number',
             'foreign' => 'added_person'));

        $this->hasMany('OhrmJobCandidateHistory', array(
             'local' => 'emp_number',
             'foreign' => 'performed_by'));

        $this->hasMany('OhrmJobInterviewInterviewer', array(
             'local' => 'emp_number',
             'foreign' => 'interviewer_id'));

        $this->hasMany('OhrmJobVacancy', array(
             'local' => 'emp_number',
             'foreign' => 'hiring_manager_id'));

        $this->hasMany('OhrmLeaveAdjustment', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('OhrmLeaveComment', array(
             'local' => 'emp_number',
             'foreign' => 'created_by_emp_number'));

        $this->hasMany('OhrmLeaveEntitlement', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('OhrmLeaveRequest', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('OhrmLeaveRequestComment', array(
             'local' => 'emp_number',
             'foreign' => 'created_by_emp_number'));

        $this->hasMany('OhrmPerformanceReview', array(
             'local' => 'emp_number',
             'foreign' => 'employee_number'));

        $this->hasMany('OhrmPerformanceTrack', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('OhrmPerformanceTrack as OhrmPerformanceTrack_2', array(
             'local' => 'emp_number',
             'foreign' => 'added_by'));

        $this->hasMany('OhrmPerformanceTrackerLog', array(
             'local' => 'emp_number',
             'foreign' => 'reviewer_id'));

        $this->hasMany('OhrmPerformanceTrackerReviewer', array(
             'local' => 'emp_number',
             'foreign' => 'reviewer_id'));

        $this->hasMany('OhrmProjectAdmin', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('OhrmUser', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));
    }
}