<?php

/**
 * BaseDistrict
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $district_code
 * @property string $district_name
 * @property string $division_code
 * @property string $province_code
 * @property Division $division
 * @property Doctrine_Collection $Thana
 * 
 * @method string              getDistrictCode()  Returns the current record's "district_code" value
 * @method string              getDistrictName()  Returns the current record's "district_name" value
 * @method string              getDivisionCode()  Returns the current record's "division_code" value
 * @method string              getProvinceCode()  Returns the current record's "province_code" value
 * @method Division            getDivision()      Returns the current record's "division" value
 * @method Doctrine_Collection getThana()         Returns the current record's "Thana" collection
 * @method District            setDistrictCode()  Sets the current record's "district_code" value
 * @method District            setDistrictName()  Sets the current record's "district_name" value
 * @method District            setDivisionCode()  Sets the current record's "division_code" value
 * @method District            setProvinceCode()  Sets the current record's "province_code" value
 * @method District            setDivision()      Sets the current record's "division" value
 * @method District            setThana()         Sets the current record's "Thana" collection
 * 
 * @package    orangehrm
 * @subpackage model\admin\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDistrict extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_district');
        $this->hasColumn('district_code', 'string', 13, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 13,
             ));
        $this->hasColumn('district_name', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('division_code', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('province_code', 'string', 13, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 13,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Division as division', array(
             'local' => 'division_code',
             'foreign' => 'division_code'));

        $this->hasMany('Thana', array(
             'local' => 'district_code',
             'foreign' => 'district_code'));
    }
}