<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmorganizationgeninfo extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_organization_gen_info', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => 100,
             ),
             'tax_id' => 
             array(
              'type' => 'string',
              'length' => 30,
              'alias' => 'taxId',
             ),
             'registration_number' => 
             array(
              'type' => 'string',
              'length' => 30,
              'alias' => 'registraionNumber',
             ),
             'phone' => 
             array(
              'type' => 'string',
              'length' => 30,
             ),
             'fax' => 
             array(
              'type' => 'string',
              'length' => 30,
             ),
             'email' => 
             array(
              'type' => 'string',
              'length' => 30,
             ),
             'country' => 
             array(
              'type' => 'string',
              'length' => 30,
             ),
             'province' => 
             array(
              'type' => 'string',
              'length' => 30,
             ),
             'city' => 
             array(
              'type' => 'string',
              'length' => 30,
             ),
             'zip_code' => 
             array(
              'type' => 'string',
              'length' => 30,
              'alias' => 'zipCode',
             ),
             'street1' => 
             array(
              'type' => 'string',
              'length' => 100,
             ),
             'street2' => 
             array(
              'type' => 'string',
              'length' => 100,
             ),
             'note' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_organization_gen_info');
    }
}