<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('hs_hr_employee', 'thana_code', 'string', '100', array(
             'default' => '',
             'alias' => 'thana',
             ));
    }

    public function down()
    {
        $this->removeColumn('hs_hr_employee', 'thana_code');
    }
}