<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmopenidprovider extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_openid_provider', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
              'alias' => 'providerId',
             ),
             'provider_name' => 
             array(
              'type' => 'string',
              'length' => 40,
              'alias' => 'providerName',
             ),
             'provider_url' => 
             array(
              'type' => 'string',
              'length' => 250,
              'alias' => 'providerUrl',
             ),
             'status' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_openid_provider');
    }
}