<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmmenuitem extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_menu_item', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
             ),
             'menu_title' => 
             array(
              'type' => 'string',
              'length' => 255,
              'alias' => 'menuTitle',
             ),
             'screen_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'alias' => 'screenId',
             ),
             'parent_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'alias' => 'parentId',
             ),
             'level' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'order_hint' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'alias' => 'orderHint',
             ),
             'url_extras' => 
             array(
              'type' => 'string',
              'length' => 255,
              'alias' => 'urlExtras',
             ),
             'status' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_menu_item');
    }
}