<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmskill extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_skill', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => 120,
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => 2147483647,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_skill');
    }
}