<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addhshremplocations extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('hs_hr_emp_locations', array(
             'emp_number' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
              'alias' => 'empNumber',
             ),
             'location_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
              'alias' => 'locationId',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'emp_number',
              1 => 'location_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('hs_hr_emp_locations');
    }
}