<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addhshrempdependents extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('hs_hr_emp_dependents', array(
             'emp_number' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
             ),
             'ed_seqno' => 
             array(
              'type' => 'decimal',
              'primary' => true,
              'length' => 2,
              'alias' => 'seqno',
             ),
             'ed_name' => 
             array(
              'type' => 'string',
              'default' => '',
              'length' => 100,
              'alias' => 'name',
             ),
             'ed_relationship_type' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'child',
              1 => 'other',
              ),
              'length' => NULL,
              'alias' => 'relationship_type',
             ),
             'ed_relationship' => 
             array(
              'type' => 'string',
              'default' => '',
              'length' => 100,
              'alias' => 'relationship',
             ),
             'ed_date_of_birth' => 
             array(
              'type' => 'date',
              'length' => 25,
              'alias' => 'date_of_birth',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'emp_number',
              1 => 'ed_seqno',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('hs_hr_emp_dependents');
    }
}