<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmprojectactivity extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_project_activity', array(
             'activity_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
              'alias' => 'activityId',
             ),
             'project_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 4,
              'alias' => 'projectId',
             ),
             'is_deleted' => 
             array(
              'type' => 'integer',
              'default' => '0',
              'length' => 1,
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => 110,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'activity_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_project_activity');
    }
}