<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmdatapointtype extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_datapoint_type', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 100,
             ),
             'action_class' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
              'alias' => 'actionClass',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_datapoint_type');
    }
}