<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmproject extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_project', array(
             'project_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
              'alias' => 'projectId',
             ),
             'customer_id' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'alias' => 'customerId',
             ),
             'is_deleted' => 
             array(
              'type' => 'integer',
              'default' => '0',
              'length' => 1,
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => 100,
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => 256,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'project_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_project');
    }
}