<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmemptermination extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_emp_termination', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'emp_number' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'alias' => 'empNumber',
             ),
             'reason_id' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'alias' => 'reasonId',
             ),
             'termination_date' => 
             array(
              'type' => 'date',
              'length' => 25,
              'alias' => 'date',
             ),
             'note' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_emp_termination');
    }
}