<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmroleuserselectionrule extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_role_user_selection_rule', array(
             'user_role_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
             ),
             'selection_rule_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
             ),
             'configurable_params' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'user_role_id',
              1 => 'selection_rule_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_role_user_selection_rule');
    }
}