<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addhshrcustomfields extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('hs_hr_custom_fields', array(
             'field_num' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
              'alias' => 'id',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 250,
             ),
             'type' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 4,
             ),
             'screen' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => 100,
             ),
             'extra_data' => 
             array(
              'type' => 'string',
              'length' => 250,
              'alias' => 'extraData',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'field_num',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('hs_hr_custom_fields');
    }
}