<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmreviewer extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_reviewer', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 6,
             ),
             'review_id' => 
             array(
              'type' => 'integer',
              'length' => 11,
              'alias' => 'reviewId',
             ),
             'employee_number' => 
             array(
              'type' => 'integer',
              'length' => 11,
              'alias' => 'employeeNumber',
             ),
             'status' => 
             array(
              'type' => 'integer',
              'length' => 11,
             ),
             'reviewer_group_id' => 
             array(
              'type' => 'integer',
              'length' => 11,
              'alias' => 'reviewerGroupId',
             ),
             'completed_date' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
              'alias' => 'completedDate',
             ),
             'comment' => 
             array(
              'type' => 'clob',
              'length' => 65532,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_reviewer');
    }
}