<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmdisplayfieldgroup extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_display_field_group', array(
             'id' => 
             array(
              'type' => 'integer',
              'unsigned' => true,
              'primary' => true,
              'length' => 8,
             ),
             'report_group_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'is_list' => 
             array(
              'type' => 'boolean',
              'notnull' => true,
              'default' => 0,
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_display_field_group');
    }
}