<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmcompositedisplayfield extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_composite_display_field', array(
             'report_group_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
              'alias' => 'reportGroupId',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'label' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'field_alias' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => 255,
              'alias' => 'fieldAlias',
             ),
             'is_sortable' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 10,
              'alias' => 'isSortable',
             ),
             'sort_order' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => 255,
              'alias' => 'sortOrder',
             ),
             'sort_field' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => 255,
              'alias' => 'sortField',
             ),
             'element_type' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
              'alias' => 'elementType',
             ),
             'element_property' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 1000,
              'alias' => 'elementProperty',
             ),
             'width' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'is_exportable' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => 10,
              'alias' => 'isExportable',
             ),
             'text_alignment_style' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => 20,
              'alias' => 'textAlignmentStyle',
             ),
             'is_value_list' => 
             array(
              'type' => 'boolean',
              'notnull' => true,
              'length' => 25,
              'alias' => 'isValueList',
             ),
             'display_field_group_id' => 
             array(
              'type' => 'integer',
              'unsigned' => true,
              'notnull' => false,
              'length' => 8,
             ),
             'default_value' => 
             array(
              'type' => 'string',
              'length' => 255,
              'alias' => 'defaultValue',
             ),
             'is_encrypted' => 
             array(
              'type' => 'boolean',
              'notnull' => true,
              'length' => 25,
              'alias' => 'isEncrypted',
             ),
             'is_meta' => 
             array(
              'type' => 'boolean',
              'notnull' => true,
              'default' => 0,
              'length' => 25,
             ),
             'composite_display_field_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
              'alias' => 'compositeDisplayFieldId',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'composite_display_field_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_composite_display_field');
    }
}