<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmemployeeworkshift extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_employee_work_shift', array(
             'work_shift_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
              'alias' => 'workShiftId',
             ),
             'emp_number' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'work_shift_id',
              1 => 'emp_number',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_employee_work_shift');
    }
}