<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmoperationalcountry extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_operational_country', array(
             'id' => 
             array(
              'type' => 'integer',
              'autoincrement' => true,
              'primary' => true,
              'length' => 4,
             ),
             'country_code' => 
             array(
              'type' => 'string',
              'length' => 3,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_operational_country');
    }
}