<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addhshrprovince extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('hs_hr_province', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'province_name' => 
             array(
              'type' => 'string',
              'default' => '',
              'notnull' => true,
              'length' => 40,
             ),
             'province_code' => 
             array(
              'type' => 'string',
              'fixed' => 1,
              'default' => '',
              'notnull' => true,
              'length' => 2,
             ),
             'cou_code' => 
             array(
              'type' => 'string',
              'fixed' => 1,
              'default' => 'us',
              'notnull' => true,
              'length' => 2,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('hs_hr_province');
    }
}