<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmworkshift extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_work_shift', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 260,
             ),
             'hours_per_day' => 
             array(
              'type' => 'decimal',
              'notnull' => true,
              'scale' => false,
              'length' => 4,
              'alias' => 'hoursPerDay',
             ),
             'start_time' => 
             array(
              'type' => 'time',
              'notnull' => true,
              'length' => 25,
             ),
             'end_time' => 
             array(
              'type' => 'time',
              'notnull' => 'true;',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_work_shift');
    }
}