<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmprojectadmin extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_project_admin', array(
             'project_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
              'alias' => 'projectId',
             ),
             'emp_number' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
              'alias' => 'empNumber',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'project_id',
              1 => 'emp_number',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_project_admin');
    }
}