<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmleavecomment extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_leave_comment', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'leave_id' => 
             array(
              'type' => 'integer',
              'unsigned' => true,
              'notnull' => true,
              'length' => 4,
             ),
             'created' => 
             array(
              'type' => 'datetime',
              'fixed' => 0,
              'unsigned' => false,
              'primary' => false,
              'notnull' => false,
              'autoincrement' => false,
              'length' => NULL,
             ),
             'created_by_name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'created_by_id' => 
             array(
              'type' => 'integer',
              'notnull' => false,
              'length' => 10,
             ),
             'created_by_emp_number' => 
             array(
              'type' => 'integer',
              'notnull' => false,
              'length' => 4,
             ),
             'comments' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_leave_comment');
    }
}