<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addhshremppassport extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('hs_hr_emp_passport', array(
             'emp_number' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
              'alias' => 'empNumber',
             ),
             'ep_seqno' => 
             array(
              'type' => 'decimal',
              'primary' => true,
              'length' => 2,
              'alias' => 'recordId',
             ),
             'ep_passport_num' => 
             array(
              'type' => 'string',
              'default' => '',
              'notnull' => true,
              'length' => 100,
              'alias' => 'number',
             ),
             'ep_i9_status' => 
             array(
              'type' => 'string',
              'default' => '',
              'length' => 100,
              'alias' => 'status',
             ),
             'ep_passportissueddate' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
              'alias' => 'issuedDate',
             ),
             'ep_passportexpiredate' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
              'alias' => 'expiryDate',
             ),
             'ep_comments' => 
             array(
              'type' => 'string',
              'length' => 255,
              'alias' => 'notes',
             ),
             'ep_passport_type_flg' => 
             array(
              'type' => 'integer',
              'length' => 2,
              'alias' => 'type',
             ),
             'ep_i9_review_date' => 
             array(
              'type' => 'date',
              'length' => 25,
              'alias' => 'reviewDate',
             ),
             'cou_code' => 
             array(
              'type' => 'string',
              'length' => 6,
              'alias' => 'countryCode',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'emp_number',
              1 => 'ep_seqno',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('hs_hr_emp_passport');
    }
}