<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmreportgroup extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_report_group', array(
             'report_group_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
              'alias' => 'reportGroupId',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'core_sql' => 
             array(
              'type' => 'clob',
              'notnull' => true,
              'length' => NULL,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'report_group_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_report_group');
    }
}