<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmselecteddisplayfieldgroup extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_selected_display_field_group', array(
             'id' => 
             array(
              'type' => 'integer',
              'unsigned' => true,
              'primary' => true,
              'length' => 8,
             ),
             'report_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'display_field_group_id' => 
             array(
              'type' => 'int',
              'unsigned' => true,
              'notnull' => true,
              'length' => NULL,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_selected_display_field_group');
    }
}