<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmperformancereview extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_performance_review', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 6,
             ),
             'status_id' => 
             array(
              'type' => 'integer',
              'length' => 11,
              'alias' => 'statusId',
             ),
             'employee_number' => 
             array(
              'type' => 'integer',
              'length' => 11,
              'alias' => 'employeeNumber',
             ),
             'work_period_start' => 
             array(
              'type' => 'date',
              'length' => 25,
              'alias' => 'workPeriodStart',
             ),
             'work_period_end' => 
             array(
              'type' => 'date',
              'length' => 25,
              'alias' => 'workPeriodEnd',
             ),
             'job_title_code' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'alias' => 'jobTitleCode',
             ),
             'department_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'alias' => 'departmentId',
             ),
             'due_date' => 
             array(
              'type' => 'date',
              'length' => 25,
              'alias' => 'dueDate',
             ),
             'completed_date' => 
             array(
              'type' => 'date',
              'length' => 25,
              'alias' => 'completedDate',
             ),
             'activated_date' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
              'alias' => 'activatedDate',
             ),
             'final_comment' => 
             array(
              'type' => 'clob',
              'length' => 65532,
              'alias' => 'finalComment',
             ),
             'final_rate' => 
             array(
              'type' => 'decimal',
              'length' => 18,
              'alias' => 'finalRate',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_performance_review');
    }
}