<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addhshrempchildren extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('hs_hr_emp_children', array(
             'emp_number' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
             ),
             'ec_seqno' => 
             array(
              'type' => 'decimal',
              'primary' => true,
              'length' => 2,
              'alias' => 'seqno',
             ),
             'ec_name' => 
             array(
              'type' => 'string',
              'default' => '',
              'length' => 100,
              'alias' => 'name',
             ),
             'ec_date_of_birth' => 
             array(
              'type' => 'date',
              'length' => 25,
              'alias' => 'dob',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'emp_number',
              1 => 'ec_seqno',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('hs_hr_emp_children');
    }
}