<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmlogin extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_login', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
              'alias' => 'userId',
             ),
             'user_name' => 
             array(
              'type' => 'string',
              'length' => 255,
              'alias' => 'userName',
             ),
             'user_role_name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
              'alias' => 'userRoleName',
             ),
             'user_role_predefined' => 
             array(
              'type' => 'boolean',
              'notnull' => true,
              'length' => 25,
              'alias' => 'userRolePredefined',
             ),
             'login_time' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
              'alias' => 'loginTime',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_login');
    }
}