<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addhshrempreportto extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('hs_hr_emp_reportto', array(
             'erep_sup_emp_number' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
              'alias' => 'supervisorId',
             ),
             'erep_sub_emp_number' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
              'alias' => 'subordinateId',
             ),
             'erep_reporting_mode' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
              'alias' => 'reportingMethodId',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'erep_sup_emp_number',
              1 => 'erep_sub_emp_number',
              2 => 'erep_reporting_mode',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('hs_hr_emp_reportto');
    }
}