<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmwsconsumer extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_ws_consumer', array(
             'app_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
             ),
             'app_token' => 
             array(
              'type' => 'string',
              'length' => 10,
             ),
             'app_name' => 
             array(
              'type' => 'string',
              'length' => 50,
             ),
             'status' => 
             array(
              'type' => 'int',
              'length' => NULL,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'app_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_ws_consumer');
    }
}