<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmempreportingmethod extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_emp_reporting_method', array(
             'reporting_method_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
              'alias' => 'id',
             ),
             'reporting_method_name' => 
             array(
              'type' => 'string',
              'length' => 100,
              'alias' => 'name',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'reporting_method_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_emp_reporting_method');
    }
}