<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmopeniduseridentity extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_openid_user_identity', array(
             'user_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             'provider_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             'user_identity' => 
             array(
              'type' => 'string',
              'length' => 2000,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'user_id',
              1 => 'provider_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_openid_user_identity');
    }
}