<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmattendancerecord extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_attendance_record', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             'employee_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
              'alias' => 'employeeId',
             ),
             'punch_in_utc_time' => 
             array(
              'type' => 'datetime',
              'length' => NULL,
              'alias' => 'punchInUtcTime',
             ),
             'punch_in_note' => 
             array(
              'type' => 'string',
              'length' => 255,
              'alias' => 'punchInNote',
             ),
             'punch_in_time_offset' => 
             array(
              'type' => 'string',
              'length' => 255,
              'alias' => 'punchInTimeOffset',
             ),
             'punch_in_user_time' => 
             array(
              'type' => 'datetime',
              'length' => NULL,
              'alias' => 'punchInUserTime',
             ),
             'punch_out_utc_time' => 
             array(
              'type' => 'datetime',
              'length' => NULL,
              'alias' => 'punchOutUtcTime',
             ),
             'punch_out_note' => 
             array(
              'type' => 'string',
              'length' => 255,
              'alias' => 'punchOutNote',
             ),
             'punch_out_time_offset' => 
             array(
              'type' => 'string',
              'length' => 255,
              'alias' => 'punchOutTimeOffset',
             ),
             'punch_out_user_time' => 
             array(
              'type' => 'datetime',
              'length' => NULL,
              'alias' => 'punchOutUserTime',
             ),
             'state' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_attendance_record');
    }
}