<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmlocation extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_location', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 13,
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => 110,
             ),
             'country_code' => 
             array(
              'type' => 'string',
              'length' => 3,
              'alias' => 'countryCode',
             ),
             'province' => 
             array(
              'type' => 'string',
              'length' => 60,
             ),
             'city' => 
             array(
              'type' => 'string',
              'length' => 60,
             ),
             'address' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'zip_code' => 
             array(
              'type' => 'string',
              'length' => 35,
              'alias' => 'zipCode',
             ),
             'phone' => 
             array(
              'type' => 'string',
              'length' => 35,
             ),
             'fax' => 
             array(
              'type' => 'string',
              'length' => 35,
             ),
             'notes' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_location');
    }
}