<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmkpi extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_kpi', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 6,
             ),
             'job_title_code' => 
             array(
              'type' => 'string',
              'length' => 10,
              'alias' => 'jobTitleCode',
             ),
             'kpi_indicators' => 
             array(
              'type' => 'varchar',
              'length' => 255,
             ),
             'min_rating' => 
             array(
              'type' => 'integer',
              'length' => 11,
             ),
             'max_rating' => 
             array(
              'type' => 'integer',
              'length' => 11,
             ),
             'default_kpi' => 
             array(
              'type' => 'integer',
              'length' => 2,
             ),
             'deleted_at' => 
             array(
              'notnull' => false,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_kpi');
    }
}