<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addhshrempdirectdebit extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('hs_hr_emp_directdebit', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'salary_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 4,
             ),
             'dd_routing_num' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 9,
              'alias' => 'routing_num',
             ),
             'dd_account' => 
             array(
              'type' => 'string',
              'default' => '',
              'notnull' => true,
              'length' => 100,
              'alias' => 'account',
             ),
             'dd_amount' => 
             array(
              'type' => 'decimal',
              'notnull' => true,
              'scale' => false,
              'length' => 11,
              'alias' => 'amount',
             ),
             'dd_account_type' => 
             array(
              'type' => 'string',
              'default' => '',
              'notnull' => true,
              'length' => 20,
              'alias' => 'account_type',
             ),
             'dd_transaction_type' => 
             array(
              'type' => 'string',
              'default' => '',
              'notnull' => true,
              'length' => 20,
              'alias' => 'transaction_type',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('hs_hr_emp_directdebit');
    }
}