<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addhshrempcontractextend extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('hs_hr_emp_contract_extend', array(
             'emp_number' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
             ),
             'econ_extend_id' => 
             array(
              'type' => 'decimal',
              'primary' => true,
              'length' => 10,
              'alias' => 'contract_id',
             ),
             'econ_extend_start_date' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
              'alias' => 'start_date',
             ),
             'econ_extend_end_date' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
              'alias' => 'end_date',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'emp_number',
              1 => 'econ_extend_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('hs_hr_emp_contract_extend');
    }
}