<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmjobtitle extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_job_title', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 13,
             ),
             'job_title' => 
             array(
              'type' => 'string',
              'length' => 100,
              'alias' => 'jobTitleName',
             ),
             'job_description' => 
             array(
              'type' => 'string',
              'length' => 400,
              'alias' => 'jobDescription',
             ),
             'note' => 
             array(
              'type' => 'string',
              'length' => 400,
             ),
             'is_deleted' => 
             array(
              'type' => 'integer',
              'default' => '0',
              'length' => 1,
              'alias' => 'isDeleted',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_job_title');
    }
}