<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmoauthclient extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_oauth_client', array(
             'client_id' => 
             array(
              'type' => 'string',
              'primary' => true,
              'length' => 80,
              'alias' => 'clientId',
             ),
             'client_secret' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 80,
              'alias' => 'clientSecret',
             ),
             'redirect_uri' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 2000,
              'alias' => 'redirectUri',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'client_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_oauth_client');
    }
}