<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmjobspecificationattachment extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_job_specification_attachment', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 13,
             ),
             'job_title_id' => 
             array(
              'type' => 'integer',
              'length' => 13,
              'alias' => 'jobTitleId',
             ),
             'file_name' => 
             array(
              'type' => 'string',
              'length' => 255,
              'alias' => 'fileName',
             ),
             'file_type' => 
             array(
              'type' => 'string',
              'length' => 255,
              'alias' => 'fileType',
             ),
             'file_size' => 
             array(
              'type' => 'integer',
              'length' => 30,
              'alias' => 'fileSize',
             ),
             'file_content' => 
             array(
              'type' => 'blob',
              'length' => 2147483647,
              'alias' => 'fileContent',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_job_specification_attachment');
    }
}