<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmreport extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_report', array(
             'report_id' => 
             array(
              'autoincrement' => true,
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
              'alias' => 'reportId',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'report_group_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
              'alias' => 'reportGroupId',
             ),
             'use_filter_field' => 
             array(
              'type' => 'boolean',
              'notnull' => true,
              'length' => 25,
              'alias' => 'useFilterField',
             ),
             'type' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'report_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_report');
    }
}