<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmbeaconnotification extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_beacon_notification', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 100,
             ),
             'expiry_date' => 
             array(
              'type' => 'timestamp',
              'notnull' => true,
              'length' => 25,
              'alias' => 'expiryDate',
             ),
             'definition' => 
             array(
              'type' => 'clob',
              'notnull' => true,
              'length' => NULL,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_beacon_notification');
    }
}