<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmuserrole extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_user_role', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'display_name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'is_assignable' => 
             array(
              'type' => 'boolean',
              'notnull' => true,
              'length' => 25,
             ),
             'is_predefined' => 
             array(
              'type' => 'boolean',
              'notnull' => true,
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_user_role');
    }
}