<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addhshrempworkexperience extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('hs_hr_emp_work_experience', array(
             'emp_number' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
             ),
             'eexp_seqno' => 
             array(
              'type' => 'decimal',
              'primary' => true,
              'length' => 10,
              'alias' => 'seqno',
             ),
             'eexp_employer' => 
             array(
              'type' => 'string',
              'length' => 100,
              'alias' => 'employer',
             ),
             'eexp_jobtit' => 
             array(
              'type' => 'string',
              'length' => 120,
              'alias' => 'jobtitle',
             ),
             'eexp_from_date' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
              'alias' => 'from_date',
             ),
             'eexp_to_date' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
              'alias' => 'to_date',
             ),
             'eexp_comments' => 
             array(
              'type' => 'string',
              'length' => 200,
              'alias' => 'comments',
             ),
             'eexp_internal' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'alias' => 'internal',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'emp_number',
              1 => 'eexp_seqno',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('hs_hr_emp_work_experience');
    }
}