<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addhshrempmemberdetail extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('hs_hr_emp_member_detail', array(
             'emp_number' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
              'alias' => 'empNumber',
             ),
             'membship_code' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
              'alias' => 'membershipId',
             ),
             'ememb_subscript_amount' => 
             array(
              'type' => 'decimal',
              'scale' => false,
              'length' => 15,
              'alias' => 'subscriptionFee',
             ),
             'ememb_subscript_ownership' => 
             array(
              'type' => 'string',
              'default' => '',
              'length' => 30,
              'alias' => 'subscriptionPaidBy',
             ),
             'ememb_subs_currency' => 
             array(
              'type' => 'string',
              'default' => '',
              'length' => 13,
              'alias' => 'subscriptionCurrency',
             ),
             'ememb_commence_date' => 
             array(
              'type' => 'date',
              'length' => 25,
              'alias' => 'subscriptionCommenceDate',
             ),
             'ememb_renewal_date' => 
             array(
              'type' => 'date',
              'length' => 25,
              'alias' => 'subscriptionRenewalDate',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'emp_number',
              1 => 'membship_code',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('hs_hr_emp_member_detail');
    }
}