<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addhshrcountry extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('hs_hr_country', array(
             'cou_code' => 
             array(
              'type' => 'string',
              'fixed' => 1,
              'primary' => true,
              'length' => 2,
             ),
             'name' => 
             array(
              'type' => 'string',
              'default' => '',
              'notnull' => true,
              'length' => 80,
             ),
             'cou_name' => 
             array(
              'type' => 'string',
              'default' => '',
              'notnull' => true,
              'length' => 80,
             ),
             'iso3' => 
             array(
              'type' => 'string',
              'fixed' => 1,
              'length' => 3,
             ),
             'numcode' => 
             array(
              'type' => 'integer',
              'length' => 2,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'cou_code',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('hs_hr_country');
    }
}