<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addhshremployee extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('hs_hr_employee', array(
             'emp_number' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
              'alias' => 'empNumber',
             ),
             'emp_lastname' => 
             array(
              'type' => 'string',
              'default' => '',
              'notnull' => true,
              'length' => 100,
              'alias' => 'lastName',
             ),
             'emp_firstname' => 
             array(
              'type' => 'string',
              'default' => '',
              'notnull' => true,
              'length' => 100,
              'alias' => 'firstName',
             ),
             'emp_middle_name' => 
             array(
              'type' => 'string',
              'default' => '',
              'notnull' => true,
              'length' => 100,
              'alias' => 'middleName',
             ),
             'emp_nick_name' => 
             array(
              'type' => 'string',
              'default' => '',
              'length' => 100,
              'alias' => 'nickName',
             ),
             'emp_smoker' => 
             array(
              'type' => 'integer',
              'default' => '0',
              'length' => 2,
              'alias' => 'smoker',
             ),
             'emp_ssn_num' => 
             array(
              'type' => 'string',
              'default' => '',
              'length' => 100,
              'alias' => 'ssn',
             ),
             'emp_sin_num' => 
             array(
              'type' => 'string',
              'default' => '',
              'length' => 100,
              'alias' => 'sin',
             ),
             'emp_other_id' => 
             array(
              'type' => 'string',
              'default' => '',
              'length' => 100,
              'alias' => 'otherId',
             ),
             'emp_dri_lice_num' => 
             array(
              'type' => 'string',
              'default' => '',
              'length' => 100,
              'alias' => 'licenseNo',
             ),
             'emp_military_service' => 
             array(
              'type' => 'string',
              'default' => '',
              'length' => 100,
              'alias' => 'militaryService',
             ),
             'emp_street1' => 
             array(
              'type' => 'string',
              'default' => '',
              'length' => 100,
              'alias' => 'street1',
             ),
             'emp_street2' => 
             array(
              'type' => 'string',
              'default' => '',
              'length' => 100,
              'alias' => 'street2',
             ),
             'city_code' => 
             array(
              'type' => 'string',
              'default' => '',
              'length' => 100,
              'alias' => 'city',
             ),
             'coun_code' => 
             array(
              'type' => 'string',
              'default' => '',
              'length' => 100,
              'alias' => 'country',
             ),
             'provin_code' => 
             array(
              'type' => 'string',
              'default' => '',
              'length' => 100,
              'alias' => 'province',
             ),
             'employee_id' => 
             array(
              'type' => 'string',
              'default' => '',
              'length' => 50,
              'alias' => 'employeeId',
             ),
             'ethnic_race_code' => 
             array(
              'type' => 'string',
              'length' => 13,
             ),
             'emp_birthday' => 
             array(
              'type' => 'date',
              'length' => 25,
             ),
             'nation_code' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'emp_gender' => 
             array(
              'type' => 'integer',
              'length' => 2,
             ),
             'emp_marital_status' => 
             array(
              'type' => 'string',
              'length' => 20,
             ),
             'emp_dri_lice_exp_date' => 
             array(
              'type' => 'date',
              'length' => 25,
             ),
             'emp_status' => 
             array(
              'type' => 'integer',
              'length' => 13,
             ),
             'job_title_code' => 
             array(
              'type' => 'integer',
              'length' => 6,
             ),
             'eeo_cat_code' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'work_station' => 
             array(
              'type' => 'integer',
              'length' => 4,
             ),
             'emp_zipcode' => 
             array(
              'type' => 'string',
              'length' => 20,
             ),
             'emp_hm_telephone' => 
             array(
              'type' => 'string',
              'length' => 50,
             ),
             'emp_mobile' => 
             array(
              'type' => 'string',
              'length' => 50,
             ),
             'emp_work_telephone' => 
             array(
              'type' => 'string',
              'length' => 50,
             ),
             'emp_work_email' => 
             array(
              'type' => 'string',
              'length' => 50,
             ),
             'sal_grd_code' => 
             array(
              'type' => 'string',
              'length' => 13,
             ),
             'joined_date' => 
             array(
              'type' => 'date',
              'length' => 25,
             ),
             'emp_oth_email' => 
             array(
              'type' => 'string',
              'length' => 50,
             ),
             'termination_id' => 
             array(
              'type' => 'integer',
              'length' => 4,
             ),
             'custom1' => 
             array(
              'type' => 'string',
              'length' => 250,
             ),
             'custom2' => 
             array(
              'type' => 'string',
              'length' => 250,
             ),
             'custom3' => 
             array(
              'type' => 'string',
              'length' => 250,
             ),
             'custom4' => 
             array(
              'type' => 'string',
              'length' => 250,
             ),
             'custom5' => 
             array(
              'type' => 'string',
              'length' => 250,
             ),
             'custom6' => 
             array(
              'type' => 'string',
              'length' => 250,
             ),
             'custom7' => 
             array(
              'type' => 'string',
              'length' => 250,
             ),
             'custom8' => 
             array(
              'type' => 'string',
              'length' => 250,
             ),
             'custom9' => 
             array(
              'type' => 'string',
              'length' => 250,
             ),
             'custom10' => 
             array(
              'type' => 'string',
              'length' => 250,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'emp_number',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('hs_hr_employee');
    }
}