<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmjobvacancy extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_job_vacancy', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 13,
             ),
             'job_title_code' => 
             array(
              'type' => 'integer',
              'length' => 13,
              'alias' => 'jobTitleCode',
             ),
             'hiring_manager_id' => 
             array(
              'type' => 'integer',
              'length' => 13,
              'alias' => 'hiringManagerId',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => 100,
             ),
             'description' => 
             array(
              'type' => 'text',
              'length' => NULL,
             ),
             'no_of_positions' => 
             array(
              'type' => 'integer',
              'length' => 13,
              'alias' => 'noOfPositions',
             ),
             'status' => 
             array(
              'type' => 'integer',
              'length' => 4,
             ),
             'published_in_feed' => 
             array(
              'type' => 'boolean',
              'length' => 25,
              'alias' => 'publishedInFeed',
             ),
             'defined_time' => 
             array(
              'type' => 'datetime',
              'length' => NULL,
              'alias' => 'definedTime',
             ),
             'updated_time' => 
             array(
              'type' => 'datetime',
              'length' => NULL,
              'alias' => 'updatedTime',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_job_vacancy');
    }
}