<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmemplicense extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_emp_license', array(
             'emp_number' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
              'alias' => 'empNumber',
             ),
             'license_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
              'alias' => 'licenseId',
             ),
             'license_no' => 
             array(
              'type' => 'string',
              'length' => 50,
              'alias' => 'licenseNo',
             ),
             'license_issued_date' => 
             array(
              'type' => 'date',
              'length' => 25,
              'alias' => 'licenseIssuedDate',
             ),
             'license_expiry_date' => 
             array(
              'type' => 'date',
              'length' => 25,
              'alias' => 'licenseExpiryDate',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'emp_number',
              1 => 'license_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_emp_license');
    }
}