<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmpaygradecurrency extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_pay_grade_currency', array(
             'pay_grade_id' => 
             array(
              'type' => 'int',
              'primary' => true,
              'length' => NULL,
             ),
             'currency_id' => 
             array(
              'type' => 'string',
              'primary' => true,
              'length' => 6,
             ),
             'min_salary' => 
             array(
              'type' => 'float',
              'length' => 2147483647,
              'alias' => 'minSalary',
             ),
             'max_salary' => 
             array(
              'type' => 'float',
              'length' => 2147483647,
              'alias' => 'maxSalary',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'pay_grade_id',
              1 => 'currency_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_pay_grade_currency');
    }
}