<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addhshrempbasicsalary extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('hs_hr_emp_basicsalary', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'emp_number' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 4,
              'alias' => 'empNumber',
             ),
             'sal_grd_code' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'alias' => 'payGradeId',
             ),
             'currency_id' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'default' => '',
              'length' => 6,
              'alias' => 'currencyCode',
             ),
             'ebsal_basic_salary' => 
             array(
              'type' => 'string',
              'length' => 100,
              'alias' => 'amount',
             ),
             'payperiod_code' => 
             array(
              'type' => 'string',
              'length' => 13,
              'alias' => 'payPeriodId',
             ),
             'salary_component' => 
             array(
              'type' => 'string',
              'length' => 100,
              'alias' => 'salaryName',
             ),
             'comments' => 
             array(
              'type' => 'string',
              'length' => 255,
              'alias' => 'notes',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('hs_hr_emp_basicsalary');
    }
}