<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmavailablegroupfield extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_available_group_field', array(
             'report_group_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
              'alias' => 'reportGroupId',
             ),
             'group_field_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
              'alias' => 'groupFieldId',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'report_group_id',
              1 => 'group_field_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_available_group_field');
    }
}