<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmgroupfield extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_group_field', array(
             'group_field_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
              'alias' => 'groupFieldId',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'group_by_clause' => 
             array(
              'type' => 'clob',
              'notnull' => true,
              'length' => NULL,
              'alias' => 'groupByClause',
             ),
             'group_field_widget' => 
             array(
              'type' => 'string',
              'length' => 255,
              'alias' => 'groupFieldWidget',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'group_field_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_group_field');
    }
}