<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmjobcandidate extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_job_candidate', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 13,
             ),
             'first_name' => 
             array(
              'type' => 'string',
              'length' => 30,
              'alias' => 'firstName',
             ),
             'middle_name' => 
             array(
              'type' => 'string',
              'length' => 30,
              'alias' => 'middleName',
             ),
             'last_name' => 
             array(
              'type' => 'string',
              'length' => 30,
              'alias' => 'lastName',
             ),
             'email' => 
             array(
              'type' => 'string',
              'length' => 100,
             ),
             'contact_number' => 
             array(
              'type' => 'string',
              'length' => 30,
              'alias' => 'contactNumber',
             ),
             'status' => 
             array(
              'type' => 'integer',
              'length' => 4,
             ),
             'comment' => 
             array(
              'type' => 'string',
              'length' => 2147483647,
             ),
             'mode_of_application' => 
             array(
              'type' => 'integer',
              'length' => 4,
              'alias' => 'modeOfApplication',
             ),
             'date_of_application' => 
             array(
              'type' => 'date',
              'length' => 25,
              'alias' => 'dateOfApplication',
             ),
             'cv_text_version' => 
             array(
              'type' => 'string',
              'length' => 2147483647,
              'alias' => 'cvTextVersion',
             ),
             'keywords' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'added_person' => 
             array(
              'type' => 'integer',
              'length' => 13,
              'alias' => 'addedPerson',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_job_candidate');
    }
}