<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmmoduledefaultpage extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_module_default_page', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
             ),
             'module_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'user_role_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'action' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => 255,
             ),
             'enable_class' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => 100,
             ),
             'priority' => 
             array(
              'type' => 'integer',
              'default' => '0',
              'notnull' => true,
              'length' => 4,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_module_default_page');
    }
}