<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmempeducation extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_emp_education', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
             ),
             'emp_number' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'alias' => 'empNumber',
             ),
             'education_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'alias' => 'educationId',
             ),
             'institute' => 
             array(
              'type' => 'string',
              'length' => 100,
             ),
             'major' => 
             array(
              'type' => 'string',
              'length' => 100,
             ),
             'year' => 
             array(
              'type' => 'decimal',
              'length' => 4,
             ),
             'score' => 
             array(
              'type' => 'string',
              'length' => 25,
             ),
             'start_date' => 
             array(
              'type' => 'date',
              'length' => 25,
              'alias' => 'startDate',
             ),
             'end_date' => 
             array(
              'type' => 'date',
              'length' => 25,
              'alias' => 'endDate',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_emp_education');
    }
}