<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addhshremplanguage extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('hs_hr_emp_language', array(
             'emp_number' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
              'alias' => 'empNumber',
             ),
             'lang_id' => 
             array(
              'type' => 'string',
              'primary' => true,
              'length' => 13,
              'alias' => 'langId',
             ),
             'fluency' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             'competency' => 
             array(
              'type' => 'integer',
              'default' => '0',
              'length' => 8,
             ),
             'comments' => 
             array(
              'type' => 'string',
              'length' => 100,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'emp_number',
              1 => 'lang_id',
              2 => 'fluency',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('hs_hr_emp_language');
    }
}