<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmjobinterview extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_job_interview', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 13,
             ),
             'candidate_vacancy_id' => 
             array(
              'type' => 'integer',
              'length' => 13,
              'alias' => 'candidateVacancyId',
             ),
             'candidate_id' => 
             array(
              'type' => 'integer',
              'length' => 13,
              'alias' => 'candidateId',
             ),
             'interview_name' => 
             array(
              'type' => 'string',
              'length' => 100,
              'alias' => 'interviewName',
             ),
             'interview_date' => 
             array(
              'type' => 'date',
              'length' => 25,
              'alias' => 'interviewDate',
             ),
             'interview_time' => 
             array(
              'type' => 'string',
              'length' => 30,
              'alias' => 'interviewTime',
             ),
             'note' => 
             array(
              'type' => 'string',
              'length' => 2147483647,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_job_interview');
    }
}