<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmtimesheetactionlog extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_timesheet_action_log', array(
             'timesheet_action_log_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
              'alias' => 'timesheetActionLogId',
             ),
             'timesheet_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'alias' => 'timesheetId',
             ),
             'performed_by' => 
             array(
              'type' => 'string',
              'length' => 255,
              'alias' => 'performedBy',
             ),
             'action' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'comment' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'date_time' => 
             array(
              'type' => 'date',
              'length' => 25,
              'alias' => 'dateTime',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'timesheet_action_log_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_timesheet_action_log');
    }
}