<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmauthproviderextradetails extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_auth_provider_extra_details', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'provider_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'provider_type' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'client_id' => 
             array(
              'type' => 'string',
              'length' => 2000,
             ),
             'client_secret' => 
             array(
              'type' => 'string',
              'length' => 2000,
             ),
             'developer_key' => 
             array(
              'type' => 'string',
              'length' => 2000,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_auth_provider_extra_details');
    }
}