<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmemailconfiguration extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_email_configuration', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
             ),
             'mail_type' => 
             array(
              'type' => 'string',
              'length' => 50,
              'alias' => 'mailType',
             ),
             'sent_as' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 250,
              'alias' => 'sentAs',
             ),
             'sendmail_path' => 
             array(
              'type' => 'string',
              'length' => 250,
              'alias' => 'sendmailPath',
             ),
             'smtp_host' => 
             array(
              'type' => 'string',
              'length' => 250,
              'alias' => 'smtpHost',
             ),
             'smtp_port' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'alias' => 'smtpPort',
             ),
             'smtp_username' => 
             array(
              'type' => 'string',
              'length' => 250,
              'alias' => 'smtpUsername',
             ),
             'smtp_password' => 
             array(
              'type' => 'string',
              'length' => 250,
              'alias' => 'smtpPassword',
             ),
             'smtp_auth_type' => 
             array(
              'type' => 'string',
              'length' => 50,
              'alias' => 'smtpAuthType',
             ),
             'smtp_security_type' => 
             array(
              'type' => 'string',
              'length' => 50,
              'alias' => 'smtpSecurityType',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_email_configuration');
    }
}