<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmtimesheet extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_timesheet', array(
             'timesheet_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
              'alias' => 'timesheetId',
             ),
             'employee_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
              'alias' => 'employeeId',
             ),
             'state' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'start_date' => 
             array(
              'type' => 'date',
              'notnull' => true,
              'length' => 25,
              'alias' => 'startDate',
             ),
             'end_date' => 
             array(
              'type' => 'date',
              'notnull' => true,
              'length' => 25,
              'alias' => 'endDate',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'timesheet_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_timesheet');
    }
}