<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addhshrempattachment extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('hs_hr_emp_attachment', array(
             'emp_number' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
             ),
             'eattach_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
              'alias' => 'attach_id',
             ),
             'eattach_size' => 
             array(
              'type' => 'integer',
              'default' => '0',
              'length' => 4,
              'alias' => 'size',
             ),
             'eattach_desc' => 
             array(
              'type' => 'string',
              'length' => 200,
              'alias' => 'description',
             ),
             'eattach_filename' => 
             array(
              'type' => 'string',
              'length' => 100,
              'alias' => 'filename',
             ),
             'eattach_attachment' => 
             array(
              'type' => 'blob',
              'length' => 2147483647,
              'alias' => 'attachment',
             ),
             'eattach_type' => 
             array(
              'type' => 'string',
              'length' => 200,
              'alias' => 'file_type',
             ),
             'screen' => 
             array(
              'type' => 'string',
              'length' => 100,
             ),
             'attached_by' => 
             array(
              'type' => 'integer',
              'length' => 4,
             ),
             'attached_by_name' => 
             array(
              'type' => 'string',
              'length' => 200,
             ),
             'attached_time' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'emp_number',
              1 => 'eattach_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('hs_hr_emp_attachment');
    }
}