<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addhshrempskill extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('hs_hr_emp_skill', array(
             'emp_number' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 4,
             ),
             'skill_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
              'alias' => 'skillId',
             ),
             'years_of_exp' => 
             array(
              'type' => 'decimal',
              'length' => 2,
             ),
             'comments' => 
             array(
              'type' => 'string',
              'default' => '',
              'notnull' => true,
              'length' => 100,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'emp_number',
              1 => 'skill_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('hs_hr_emp_skill');
    }
}