<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addhshrconfig extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('hs_hr_config', array(
             '`key`' => 
             array(
              'type' => 'string',
              'primary' => true,
              'length' => 100,
              'alias' => 'key',
             ),
             'value' => 
             array(
              'type' => 'string',
              'default' => '',
              'notnull' => true,
              'length' => 512,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => '`key`',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('hs_hr_config');
    }
}