<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmjobcandidatevacancy extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_job_candidate_vacancy', array(
             'id' => 
             array(
              'type' => 'integer',
              'unique' => true,
              'length' => 13,
             ),
             'candidate_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 13,
              'alias' => 'candidateId',
             ),
             'vacancy_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 13,
              'alias' => 'vacancyId',
             ),
             'status' => 
             array(
              'type' => 'string',
              'length' => 100,
             ),
             'applied_date' => 
             array(
              'type' => 'date',
              'length' => 25,
              'alias' => 'appliedDate',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'candidate_id',
              1 => 'vacancy_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_job_candidate_vacancy');
    }
}