<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmselectedgroupfield extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_selected_group_field', array(
             'group_field_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
              'alias' => 'groupFieldId',
             ),
             'summary_display_field_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
              'alias' => 'summaryDisplayFieldId',
             ),
             'report_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
              'alias' => 'reportId',
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'group_field_id',
              1 => 'summary_display_field_id',
              2 => 'report_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_selected_group_field');
    }
}