<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmtimesheetitem extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_timesheet_item', array(
             'timesheet_item_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
              'alias' => 'timesheetItemId',
             ),
             'timesheet_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
              'alias' => 'timesheetId',
             ),
             'employee_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'alias' => 'employeeId',
             ),
             'project_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'alias' => 'projectId',
             ),
             'activity_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'alias' => 'activityId',
             ),
             'date' => 
             array(
              'type' => 'date',
              'length' => 25,
             ),
             'duration' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'comment' => 
             array(
              'type' => 'string',
              'length' => 2000,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'timesheet_item_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_timesheet_item');
    }
}