<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addohrmfilterfield extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ohrm_filter_field', array(
             'filter_field_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
              'alias' => 'filterFieldId',
             ),
             'report_group_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
              'alias' => 'reportGroupId',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'where_clause_part' => 
             array(
              'type' => 'clob',
              'notnull' => true,
              'length' => NULL,
              'alias' => 'whereClausePart',
             ),
             'filter_field_widget' => 
             array(
              'type' => 'string',
              'length' => 255,
              'alias' => 'filterFieldWidget',
             ),
             'condition_no' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
              'alias' => 'conditionNo',
             ),
             'required' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => 10,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'filter_field_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ohrm_filter_field');
    }
}