<?php

/**
 * HsHrEmpDirectdebitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HsHrEmpDirectdebitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HsHrEmpDirectdebitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HsHrEmpDirectdebit');
    }
}