<?php

/**
 * HsHrThanaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HsHrThanaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HsHrThanaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HsHrThana');
    }
}