<?php

/**
 * OhrmLeaveEntitlementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmLeaveEntitlementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmLeaveEntitlementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmLeaveEntitlement');
    }
}