<?php

/**
 * OhrmLocationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmLocationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmLocationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmLocation');
    }
}