<?php

/**
 * OhrmUserRoleScreenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmUserRoleScreenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmUserRoleScreenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmUserRoleScreen');
    }
}