<?php

/**
 * OhrmSubunitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmSubunitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmSubunitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmSubunit');
    }
}