<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/11/05 11:06:55

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=orangehrm_mysql',
  'username' => 'orangehrm',
  'password' => 'orangehrm',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
