<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AbstractDisplayField', 'doctrine');

/**
 * BaseAbstractDisplayField
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $reportGroupId
 * @property string $name
 * @property string $label
 * @property string $fieldAlias
 * @property string $isSortable
 * @property string $sortOrder
 * @property string $sortField
 * @property string $elementType
 * @property string $elementProperty
 * @property string $width
 * @property string $isExportable
 * @property string $textAlignmentStyle
 * @property integer $isValueList
 * @property integer $display_field_group_id
 * @property string $defaultValue
 * @property integer $isEncrypted
 * @property integer $is_meta
 * @property integer $id
 * @property ReportGroup $ReportGroup
 * @property DisplayFieldGroup $DisplayFieldGroup
 * 
 * @method integer              getReportGroupId()          Returns the current record's "reportGroupId" value
 * @method string               getName()                   Returns the current record's "name" value
 * @method string               getLabel()                  Returns the current record's "label" value
 * @method string               getFieldAlias()             Returns the current record's "fieldAlias" value
 * @method string               getIsSortable()             Returns the current record's "isSortable" value
 * @method string               getSortOrder()              Returns the current record's "sortOrder" value
 * @method string               getSortField()              Returns the current record's "sortField" value
 * @method string               getElementType()            Returns the current record's "elementType" value
 * @method string               getElementProperty()        Returns the current record's "elementProperty" value
 * @method string               getWidth()                  Returns the current record's "width" value
 * @method string               getIsExportable()           Returns the current record's "isExportable" value
 * @method string               getTextAlignmentStyle()     Returns the current record's "textAlignmentStyle" value
 * @method integer              getIsValueList()            Returns the current record's "isValueList" value
 * @method integer              getDisplayFieldGroupId()    Returns the current record's "display_field_group_id" value
 * @method string               getDefaultValue()           Returns the current record's "defaultValue" value
 * @method integer              getIsEncrypted()            Returns the current record's "isEncrypted" value
 * @method integer              getIsMeta()                 Returns the current record's "is_meta" value
 * @method integer              getId()                     Returns the current record's "id" value
 * @method ReportGroup          getReportGroup()            Returns the current record's "ReportGroup" value
 * @method DisplayFieldGroup    getDisplayFieldGroup()      Returns the current record's "DisplayFieldGroup" value
 * @method AbstractDisplayField setReportGroupId()          Sets the current record's "reportGroupId" value
 * @method AbstractDisplayField setName()                   Sets the current record's "name" value
 * @method AbstractDisplayField setLabel()                  Sets the current record's "label" value
 * @method AbstractDisplayField setFieldAlias()             Sets the current record's "fieldAlias" value
 * @method AbstractDisplayField setIsSortable()             Sets the current record's "isSortable" value
 * @method AbstractDisplayField setSortOrder()              Sets the current record's "sortOrder" value
 * @method AbstractDisplayField setSortField()              Sets the current record's "sortField" value
 * @method AbstractDisplayField setElementType()            Sets the current record's "elementType" value
 * @method AbstractDisplayField setElementProperty()        Sets the current record's "elementProperty" value
 * @method AbstractDisplayField setWidth()                  Sets the current record's "width" value
 * @method AbstractDisplayField setIsExportable()           Sets the current record's "isExportable" value
 * @method AbstractDisplayField setTextAlignmentStyle()     Sets the current record's "textAlignmentStyle" value
 * @method AbstractDisplayField setIsValueList()            Sets the current record's "isValueList" value
 * @method AbstractDisplayField setDisplayFieldGroupId()    Sets the current record's "display_field_group_id" value
 * @method AbstractDisplayField setDefaultValue()           Sets the current record's "defaultValue" value
 * @method AbstractDisplayField setIsEncrypted()            Sets the current record's "isEncrypted" value
 * @method AbstractDisplayField setIsMeta()                 Sets the current record's "is_meta" value
 * @method AbstractDisplayField setId()                     Sets the current record's "id" value
 * @method AbstractDisplayField setReportGroup()            Sets the current record's "ReportGroup" value
 * @method AbstractDisplayField setDisplayFieldGroup()      Sets the current record's "DisplayFieldGroup" value
 * 
 * @package    orangehrm
 * @subpackage model\core\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAbstractDisplayField extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('abstract_display_field');
        $this->hasColumn('report_group_id as reportGroupId', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('label', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('field_alias as fieldAlias', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('is_sortable as isSortable', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('sort_order as sortOrder', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('sort_field as sortField', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('element_type as elementType', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('element_property as elementProperty', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('width', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('is_exportable as isExportable', 'string', 10, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 10,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('text_alignment_style as textAlignmentStyle', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('is_value_list as isValueList', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('display_field_group_id', 'integer', 8, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => false,
             'fixed' => 0,
             'primary' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('default_value as defaultValue', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('is_encrypted as isEncrypted', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('is_meta', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => '0',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ReportGroup', array(
             'local' => 'report_group_id',
             'foreign' => 'reportGroupId',
             'onDelete' => 'cascade'));

        $this->hasOne('DisplayFieldGroup', array(
             'local' => 'display_field_group_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}